import React, { createContext, useContext, useState, ReactNode, useEffect } from 'react';

export type Language = 'sr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, fallback?: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  sr: {
    'nav.home': 'Početna',
    'nav.events': 'Događaji',
    'nav.cart': 'Korpa',
    'nav.contact': 'Kontakt',
    'category.koncerti': 'Koncerti',
    'category.festivali': 'Festivali',
    'category.predstave': 'Predstave',
    'category.konferencije': 'Konferencije',
    'category.sajmovi': 'Sajmovi',
    'category.nova godina': 'Nova godina',
    'category.ostalo': 'Ostalo',
    'common.loading': 'Učitava...',
    'common.search': 'Pretraži',
    'common.filter': 'Filtriraj',
    'common.clear': 'Očisti',
    'common.cancel': 'Otkaži',
    'common.confirm': 'Potvrdi',
    'common.back': 'Nazad',
    'common.next': 'Sljedeće',
    'common.previous': 'Prethodno',
    'common.close': 'Zatvori',
    'common.save': 'Sačuvaj',
    'common.edit': 'Uredi',
    'common.delete': 'Obriši',
    'common.add': 'Dodaj',
    'common.remove': 'Ukloni',
    'common.view': 'Pogledaj',
    'common.download': 'Preuzmi',
    'common.share': 'Dijeli',
    'common.print': 'Štampaj',
    'common.email': 'Email',
    'common.phone': 'Telefon',
    'common.address': 'Adresa',
    'common.city': 'Grad',
    'common.date': 'Datum',
    'common.time': 'Vrijeme',
    'common.price': 'Cijena',
    'common.quantity': 'Količina',
    'common.total': 'Ukupno',
    'common.subtotal': 'Međuzbroj',
    'common.currency': 'KM',
    'home.hero.title': 'Dobrodošli na Tvoja Karta',
    'home.hero.subtitle': 'Otkrijte najuzbudljivije događaje u Banja Luci i Prijedoru',
    'home.categories.title': 'Kategorije događaja',
    'home.featured.title': 'Istaknuti događaji',
    'home.upcoming.title': 'Nadolazeći događaji',
    'events.title': 'Događaji',
    'events.search.placeholder': 'Pretraži događaje...',
    'events.filter.all': 'Svi događaji',
    'events.filter.category': 'Filtriraj po kategoriji',
    'events.filter.location': 'Filtriraj po lokaciji',
    'events.sort.date': 'Sortiraj po datumu',
    'events.sort.price': 'Sortiraj po cijeni',
    'events.sort.popularity': 'Sortiraj po popularnosti',
    'events.no_results': 'Nema rezultata',
    'events.load_more': 'Učitaj više',
    'event.details': 'Detalji događaja',
    'event.description': 'Opis',
    'event.location': 'Lokacija',
    'event.date_time': 'Datum i vrijeme',
    'event.tickets': 'Karte',
    'event.ticket_types': 'Tipovi karata',
    'event.select_ticket': 'Odaberite tip karte',
    'event.add_to_cart': 'Dodaj u korpu',
    'event.continue_to_payment': 'Nastavi na naplatu',
    'event.sold_out': 'Rasprodato',
    'event.available': 'Dostupno',
    'event.limited': 'Ograničeno',
    'cart.title': 'Korpa za kupovinu',
    'cart.empty': 'Vaša korpa je prazna',
    'cart.empty.description': 'Počnite da pregledate događaje da pronađete karte koje biste željeli kupiti',
    'cart.continue_shopping': 'Nastavi kupovinu',
    'cart.checkout': 'Nastavi na naplatu',
    'cart.clear': 'Očisti korpu',
    'cart.item.each': 'svaka',
    'cart.fees.service': 'Servisna naknada',
    'cart.fees.processing': 'Naknada za procesiranje',
    'cart.security.ssl': 'Sigurna 256-bit SSL enkripcija',
    'cart.security.cards': 'Prihvaćene sve glavne kreditne kartice',
    'cart.security.delivery': 'Trenutna dostava karata',
    'cart.security.mobile': 'QR kodovi ili bar kodovi prilagođeni mobilnim uređajima',
    'reservation.title': 'Rezervacija',
    'reservation.subtitle': 'Rezervišite vaše mjesto',
    'reservation.free_event': 'Besplatni događaj',
    'reservation.form.title': 'Podaci za rezervaciju',
    'reservation.form.first_name': 'Ime',
    'reservation.form.last_name': 'Prezime', 
    'reservation.form.email': 'Email adresa',
    'reservation.form.phone': 'Telefon (opcionalno)',
    'reservation.button': 'Rezerviši mjesto',
    'reservation.register_button': 'Registruj se',
    'reservation.email_placeholder': 'Unesite vašu email adresu',
    'reservation.success_message': 'Hvala što ste se registrovali za ovaj događaj. Uskoro ćete primiti potvrdu putem email-a.',
    'reservation.confirmation': 'Vaša rezervacija je potvrđena!',
    'reservation.confirmation.subtitle': 'Detalji rezervacije su poslani na vašu email adresu.',
    'payment.title': 'Plaćanje',
    'payment.subtitle': 'Završite svoju kupovinu',
    'payment.billing': 'Podaci za naplatu',
    'payment.card_details': 'Podaci o kartici',
    'payment.first_name': 'Ime',
    'payment.last_name': 'Prezime',
    'payment.email': 'Email adresa',
    'payment.phone': 'Telefon',
    'payment.address': 'Adresa',
    'payment.city': 'Grad',
    'payment.postal_code': 'Poštanski kod',
    'payment.card_name': 'Ime na kartici',
    'payment.card_number': 'Broj kartice',
    'payment.expiry_date': 'Datum isteka',
    'payment.cvv': 'CVV',
    'payment.terms_accept': 'Prihvatam',
    'payment.terms_of_service': 'Uslove korišćenja',
    'payment.privacy_policy': 'Politiku privatnosti',
    'payment.newsletter': 'Želim da primam obaveštenja o novim događajima i posebnim ponudama',
    'payment.processing': 'Obrađuje se...',
    'payment.pay_now': 'Izvrši plaćanje',
    'payment.order_summary': 'Pregled narudžbe',
    'payment.secure': 'Sigurno plaćanje zaštićeno SSL enkripcijom',
    'footer.company': 'Tvoja Karta',
    'footer.description': 'Pouzdan, siguran i brz sistem za kupovinu karata za sve vrste događaja.',
    'footer.quick_links': 'Brze veze',
    'footer.categories': 'Kategorije',
    'footer.legal': 'Pravni dokumenti',
    'footer.follow_us': 'Pratite nas',
    'footer.contact_info': 'Kontakt informacije',
    'footer.rights': 'Sva prava zadržana.',
    'footer.privacy': 'Politika privatnosti',
    'footer.terms': 'Uslovi korišćenja',
    'footer.cookies': 'Politika kolačića',
    'footer.navigation': 'Navigacija',
    'footer.newsletter': 'Newsletter',
    'footer.newsletter_description': 'Pretplatite se na naš newsletter da primite najnovije vijesti o događajima u blizini.',
    'footer.newsletter_placeholder': 'Unesite vašu email adresu',
    'footer.newsletter_subscribe': 'Pretplati se',
    'footer.support': 'Podrška',
    'contact.title': 'Kontaktirajte nas',
    'contact.subtitle': 'Imate pitanja? Rado ćemo vam pomoći!',
    'contact.form.name': 'Ime i prezime',
    'contact.form.email': 'Email adresa',
    'contact.form.subject': 'Predmet',
    'contact.form.message': 'Poruka',
    'contact.form.send': 'Pošaljite poruku',
    'contact.info.title': 'Kontakt informacije',
    'contact.info.address': 'Banja Luka, Bosnia and Herzegovina',
    'contact.info.phone': '+387 66 373 666',
    'contact.info.email': 'info@tvojakarta.com',
    'contact.hours.title': 'Radno vrijeme',
    'contact.hours.weekdays': 'Ponedjeljak - Petak: 9:00 - 17:00',
    'contact.hours.weekend': 'Subota - Nedjelja: 10:00 - 16:00',
    'message.success.payment': 'Plaćanje je uspješno izvršeno! Vaše karte će biti poslane na email.',
    'message.success.added_to_cart': 'Dodano u korpu',
    'message.error.required_fields': 'Molimo popunite sva potrebna polja',
    'message.error.invalid_email': 'Unesite valjanu email adresu',
    'message.error.card_number': 'Broj kartice mora imati 16 cifara',
    'message.error.cvv': 'CVV mora imati 3 cifre',
    'message.error.terms': 'Morate prihvatiti Uslove korišćenja',
    'message.error.payment': 'Došlo je do greške prilikom plaćanja. Pokušajte ponovo.',
    'newsletter.title': 'Trenutno nema dostupnih događaja',
    'newsletter.description': 'Pretplatite se na naš newsletter kako biste primili email kada novi događaj postane dostupan.',
    'newsletter.stay_updated_title': 'Ostanite u toku',
    'newsletter.stay_updated_description': 'Pretplatite se na naš newsletter i budite prvi koji će saznati o novim događajima i posebnim ponudama.',
    'newsletter.card_title': 'Pretplatite se na newsletter',
    'newsletter.card_description': 'Budite među prvima koji će saznati o novim događajima i ekskluzivnim ponudama.',
    'newsletter.email_label': 'Email adresa',
    'newsletter.email_placeholder': 'vaša.email@primjer.com',
    'newsletter.subscribe_button': 'Pretplati se',
    'newsletter.privacy_note': 'Poštujemo vašu privatnost. Vaši podaci su sigurni i neće biti dijeljeni sa trećim stranama.',
    'newsletter.success_title': 'Uspješno ste se pretplatili!',
    'newsletter.success_message': 'Hvala što ste se pretplatili. Obavijestit ćemo vas čim novi događaji postanu dostupni.',
    'newsletter.benefit1_title': 'Ažurne obavijesti',
    'newsletter.benefit1_description': 'Primajte obavijesti o novim događajima čim budu objavljeni.',
    'newsletter.benefit2_title': 'Ekskluzivne ponude',
    'newsletter.benefit2_description': 'Pristup posebnim ponudama i popustima samo za pretplatnike.',
    'newsletter.benefit3_title': 'Nikad ne propustite',
    'newsletter.benefit3_description': 'Budite prvi koji saznaju o nadolazećim koncertima i festivalima.'
  },
  en: {
    'nav.home': 'Home',
    'nav.events': 'Events',
    'nav.cart': 'Cart',
    'nav.contact': 'Contact',
    'category.koncerti': 'Concerts',
    'category.festivali': 'Festivals',
    'category.predstave': 'Shows',
    'category.konferencije': 'Conferences',
    'category.sajmovi': 'Fairs',
    'category.nova godina': 'New Year',
    'category.ostalo': 'Other',
    'common.loading': 'Loading...',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.clear': 'Clear',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.close': 'Close',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.add': 'Add',
    'common.remove': 'Remove',
    'common.view': 'View',
    'common.download': 'Download',
    'common.share': 'Share',
    'common.print': 'Print',
    'common.email': 'Email',
    'common.phone': 'Phone',
    'common.address': 'Address',
    'common.city': 'City',
    'common.date': 'Date',
    'common.time': 'Time',
    'common.price': 'Price',
    'common.quantity': 'Quantity',
    'common.total': 'Total',
    'common.subtotal': 'Subtotal',
    'common.currency': 'BAM',
    'home.hero.title': 'Welcome to Tvoja Karta',
    'home.hero.subtitle': 'Discover the most exciting events in Banja Luka and Prijedor',
    'home.categories.title': 'Event Categories',
    'home.featured.title': 'Featured Events',
    'home.upcoming.title': 'Upcoming Events',
    'events.title': 'Events',
    'events.search.placeholder': 'Search events...',
    'events.filter.all': 'All Events',
    'events.filter.category': 'Filter by Category',
    'events.filter.location': 'Filter by Location',
    'events.sort.date': 'Sort by Date',
    'events.sort.price': 'Sort by Price',
    'events.sort.popularity': 'Sort by Popularity',
    'events.no_results': 'No Results',
    'events.load_more': 'Load More',
    'event.details': 'Event Details',
    'event.description': 'Description',
    'event.location': 'Location',
    'event.date_time': 'Date & Time',
    'event.tickets': 'Tickets',
    'event.ticket_types': 'Ticket Types',
    'event.select_ticket': 'Select ticket type',
    'event.add_to_cart': 'Add to Cart',
    'event.continue_to_payment': 'Continue to Payment',
    'event.sold_out': 'Sold Out',
    'event.available': 'Available',
    'event.limited': 'Limited',
    'cart.title': 'Shopping Cart',
    'cart.empty': 'Your cart is empty',
    'cart.empty.description': 'Start browsing events to find tickets you would like to purchase',
    'cart.continue_shopping': 'Continue Shopping',
    'cart.checkout': 'Proceed to Checkout',
    'cart.clear': 'Clear Cart',
    'cart.item.each': 'each',
    'cart.fees.service': 'Service Fee',
    'cart.fees.processing': 'Processing Fee',
    'cart.security.ssl': 'Secure 256-bit SSL encryption',
    'cart.security.cards': 'All major credit cards accepted',
    'cart.security.delivery': 'Instant ticket delivery',
    'cart.security.mobile': 'Mobile-friendly QR codes or bar codes',
    'reservation.title': 'Reservation',
    'reservation.subtitle': 'Reserve your seat',
    'reservation.free_event': 'Free Event',
    'reservation.form.title': 'Reservation Details',
    'reservation.form.first_name': 'First Name',
    'reservation.form.last_name': 'Last Name',
    'reservation.form.email': 'Email Address',
    'reservation.form.phone': 'Phone (optional)',
    'reservation.button': 'Reserve Seat',
    'reservation.register_button': 'Register',
    'reservation.email_placeholder': 'Enter your email address',
    'reservation.success_message': 'Thank you for registering to this event. You will receive a confirmation email soon.',
    'reservation.confirmation': 'Your reservation is confirmed!',
    'reservation.confirmation.subtitle': 'Reservation details have been sent to your email address.',
    'payment.title': 'Payment',
    'payment.subtitle': 'Complete your purchase',
    'payment.billing': 'Billing Information',
    'payment.card_details': 'Card Details',
    'payment.first_name': 'First Name',
    'payment.last_name': 'Last Name',
    'payment.email': 'Email Address',
    'payment.phone': 'Phone',
    'payment.address': 'Address',
    'payment.city': 'City',
    'payment.postal_code': 'Postal Code',
    'payment.card_name': 'Name on Card',
    'payment.card_number': 'Card Number',
    'payment.expiry_date': 'Expiry Date',
    'payment.cvv': 'CVV',
    'payment.terms_accept': 'I accept the',
    'payment.terms_of_service': 'Terms of Service',
    'payment.privacy_policy': 'Privacy Policy',
    'payment.newsletter': 'I want to receive notifications about new events and special offers',
    'payment.processing': 'Processing...',
    'payment.pay_now': 'Pay Now',
    'payment.order_summary': 'Order Summary',
    'payment.secure': 'Secure payment protected by SSL encryption',
    'footer.company': 'Tvoja Karta',
    'footer.description': 'Reliable, safe and fast system for buying tickets for all kinds of events.',
    'footer.quick_links': 'Quick Links',
    'footer.categories': 'Categories',
    'footer.legal': 'Legal',
    'footer.follow_us': 'Follow Us',
    'footer.contact_info': 'Contact Info',
    'footer.rights': 'All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.cookies': 'Cookie Policy',
    'footer.navigation': 'Navigation',
    'footer.newsletter': 'Newsletter',
    'footer.newsletter_description': 'Subscribe to our newsletter to receive the latest news on events nearby.',
    'footer.newsletter_placeholder': 'Enter your email address',
    'footer.newsletter_subscribe': 'Subscribe',
    'footer.support': 'Support',
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Have questions? We\'d love to help!',
    'contact.form.name': 'Full Name',
    'contact.form.email': 'Email Address',
    'contact.form.subject': 'Subject',
    'contact.form.message': 'Message',
    'contact.form.send': 'Send Message',
    'contact.info.title': 'Contact Information',
    'contact.info.address': 'Banja Luka, Bosnia and Herzegovina',
    'contact.info.phone': '+387 66 373 666',
    'contact.info.email': 'info@tvojakarta.com',
    'contact.hours.title': 'Business Hours',
    'contact.hours.weekdays': 'Monday - Friday: 9:00 AM - 5:00 PM',
    'contact.hours.weekend': 'Saturday - Sunday: 10:00 AM - 4:00 PM',
    'message.success.payment': 'Payment successful! Your tickets will be sent to your email.',
    'message.success.added_to_cart': 'Added to cart',
    'message.error.required_fields': 'Please fill in all required fields',
    'message.error.invalid_email': 'Please enter a valid email address',
    'message.error.card_number': 'Card number must have 16 digits',
    'message.error.cvv': 'CVV must have 3 digits',
    'message.error.terms': 'You must accept the Terms of Service',
    'message.error.payment': 'An error occurred during payment. Please try again.',
    'newsletter.title': 'No Current Events Available',
    'newsletter.description': 'Subscribe to our newsletter to receive an email when a new event becomes available.',
    'newsletter.stay_updated_title': 'Stay Updated',
    'newsletter.stay_updated_description': 'Subscribe to our newsletter and be the first to know about new events and special offers.',
    'newsletter.card_title': 'Subscribe to Newsletter',
    'newsletter.card_description': 'Be among the first to know about new events and exclusive offers.',
    'newsletter.email_label': 'Email Address',
    'newsletter.email_placeholder': 'your.email@example.com',
    'newsletter.subscribe_button': 'Subscribe',
    'newsletter.privacy_note': 'We respect your privacy. Your data is safe and will not be shared with third parties.',
    'newsletter.success_title': 'Successfully Subscribed!',
    'newsletter.success_message': 'Thank you for subscribing. We will notify you as soon as new events become available.',
    'newsletter.benefit1_title': 'Timely Notifications',
    'newsletter.benefit1_description': 'Receive notifications about new events as soon as they are published.',
    'newsletter.benefit2_title': 'Exclusive Offers',
    'newsletter.benefit2_description': 'Access special offers and discounts only for subscribers.',
    'newsletter.benefit3_title': 'Never Miss Out',
    'newsletter.benefit3_description': 'Be the first to know about upcoming concerts and festivals.'
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('tvoja-karta-language');
    return (saved as Language) || 'sr';
  });

  useEffect(() => {
    localStorage.setItem('tvoja-karta-language', language);
  }, [language]);

  const t = (key: string, fallback?: string): string => {
    return translations[language]?.[key] || fallback || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}